"""create sos and emergency notifications tables

Revision ID: c12ff0cd8dcb
Revises: 4975c1f4f91d
Create Date: 2026-09-26 13:31:37.338521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12ff0cd8dcb'
down_revision: Union[str, None] = '4975c1f4f91d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sos_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'dispatched', 'resolved', name='sos_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_reports_user_id'), 'sos_reports', ['user_id'], unique=False)
    op.create_table('emergency_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sos_report_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'email', 'push', name='notification_channel'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', name='notification_status'), nullable=False),
    sa.ForeignKeyConstraint(['sos_report_id'], ['sos_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_notifications_sos_report_id'), 'emergency_notifications', ['sos_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergency_notifications_sos_report_id'), table_name='emergency_notifications')
    op.drop_table('emergency_notifications')
    op.drop_index(op.f('ix_sos_reports_user_id'), table_name='sos_reports')
    op.drop_table('sos_reports')
    # ### end Alembic commands ###
